### ISSUE TITLE
could you explain what does "--backend-spdy-window-bits " and "--backend-spdy-connection-window-bits"?

### ISSUE THREAD

**Issue by megarzzy** [tatsuhiro-t/spdylay#140]
--backend-spdy-window-bits=<N>
                       Sets the per-stream initial window size of
                       SPDY backend connection to 2**<N>.
                       Default: 16
    --backend-spdy-connection-window-bits=<N>
                       Sets the per-connection window size of SPDY
                       backend connection to 2**<N>.
                       Default: 16
how to tunnel the performance ? please

**Comment by tatsuhiro-t** [comment]
This is the flow control window size that backend SPDY server sends response to shrpx without acknowledgement from shrpx (more specifically, WINDOW_UPDATE).  SPDY/3.1 has 2 layer of flow control window: connection and stream.  The connection is window size across all active streams, and it has larger effect than stream level window size.  If you increase this value, it may increase memory usage of shrpx, since that amount of data is cached in memory.  So run the test and tune these options comparing throughput and memory usage.
